struct _DEV_HEADER _far *DevHeaderLocate(char *name);
int DevError(struct _DEV_REQ_HEADER *header);
void DevReqHeaderFill(struct _DEV_REQ_HEADER *hdr, unsigned char command);
void DevIOCTLFill(struct _IOCTL_HEADER *ioctl);
void DevIOCTLInputFill(struct _IOCTL_HEADER *ioctl, unsigned char code);
void DevIOCTLOutputFill(struct _IOCTL_HEADER *ioctl, unsigned char code);
int CDROMInit(char *name);
int CDROMOpen(void);
int CDROMResume(void);
int CDROMStop(void);
int CDROMClose(void);
void _far *CDROMHeader(void);
int CDROMStatus(unsigned long *status);
int CDROMHeadLocation(struct _CD_HEAD_LOCATION *where);
int CDROMAudioChannels(struct _CD_AUDIO_CHANNELS *where);
int CDROMSectorSize(struct _CD_SECTOR_SIZE *where);
int CDROMSectorInfo(unsigned long *sectors);
int CDROMMediaChanged(unsigned char *change);
int CDROMDiscInfo(struct _CD_DISC_INFO *where);
int CDROMTrackInfo(struct _CD_TRACK_INFO *where);
int CDROMAudioQChannel(struct _CD_Q_CHANNEL *where);
int CDROMUPCCode(char *where);
int CDROMAudioStatus(struct _CD_AUDIO_STATUS *where);
int CDROMEjectDisc(void);
int CDROMReset(void);
int CDROMCloseTray(void);
int CDROMAudioControl(struct _CD_AUDIO_CHANNELS *where);
int CDROMDoorControl(unsigned char lock);
int CDROMSetup(void);
void CDROMSetTrack(int i);
