void ReadXfer(unsigned int etport);
byte ET_CheckDrop(unsigned int etport);
void SetGameMode(byte *mode, byte source);
void settrack(void);
void setupslots(void);
void LOBBY_boot(void);
void LOBBY_boot(void);
void ReadScreen(char *file);
void PrintMessage(int dummy);
void LOBBY_tween();
void LOBBY_instokn();
void LOBBY_noxfer();
void Dig_Digit(int digit, byte x, byte y);
void LOBBY_alert();
void LOBBY_game1_naughty();
void LOBBY_game1();
int LOBBY_game1_teamud(int color, int naughty);
void LOBBY_game1_update(int naughty);
void LOBBY_game2();
void setupcga(byte type);
void nl_to_null(char *string);
void clrcga(void);
void effectsout(char *command, int length);
void GetRedTeam(byte teams, byte who);
void GetGrnTeam(byte teams, byte who);
void SelectTrack(byte track);
